#include "variants.h"

#define _MLA_VARIANT_IMPL(AMPCLASS, MAGCLASS, NAME) \
    IMPLEMENT_SC_CLASS_DERIVED(AMPCLASS, Amplitude_MLA, "Amplitude_" #NAME); \
    REGISTER_AMPLITUDEPROCESSOR(AMPCLASS, #NAME); \
    REGISTER_MAGNITUDEPROCESSOR(MAGCLASS, #NAME)

#define IMPLEMENT_MLA_VARIANT(NAME) \
    _MLA_VARIANT_IMPL(Amplitude_##NAME, Magnitude_##NAME, NAME)

// Register the variants with SeisComP
IMPLEMENT_MLA_VARIANT(MLa01);
IMPLEMENT_MLA_VARIANT(MLa05);
IMPLEMENT_MLA_VARIANT(MLa075);